config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:sessions, :registrations, :passwords],
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: 'registrations'
    }

  root 'challenges#index'

  # Default Devise routes
  #
  # Sessions
  # new_user_session     GET    /users/sign_in(.:format)  devise/sessions#new
  # user_session         POST   /users/sign_in(.:format)  devise/sessions#create
  # destroy_user_session DELETE /users/sign_out(.:format) devise/sessions#destroy
  #
  # Registrations
  # cancel_user_registration GET    /users/cancel(.:format)  registrations#cancel
  # user_registration        POST   /users(.:format)         registrations#create
  # new_user_registration    GET    /users/sign_up(.:format) registrations#new
  # edit_user_registration   GET    /users/edit(.:format)    registrations#edit
  #                          PATCH  /users(.:format)         registrations#update
  #                          PUT    /users(.:format)         registrations#update
  #                          DELETE /users(.:format)         registrations#destroy
  #
  # Passwords
  # user_password      POST  /users/password(.:format)      devise/passwords#create
  # new_user_password  GET   /users/password/new(.:format)  devise/passwords#new
  # edit_user_password GET   /users/password/edit(.:format) devise/passwords#edit
  #                    PATCH /users/password(.:format)      devise/passwords#update
  #                    PUT   /users/password(.:format)      devise/passwords#update

  devise_scope :user do
    # Sessions
    get    'login',  to: 'devise/sessions#new',     as: :new_user_session
    post   'login',  to: 'devise/sessions#create',  as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session

    # Registrations
    get    'signup',           to: 'registrations#new',    as: :new_user_registration
    post   'settings/account', to: 'registrations#create', as: :user_registration
    get    'settings/account', to: 'registrations#edit',   as: :edit_user_registration
    put    'settings/account', to: 'registrations#update'
    delete 'settings/account', to: 'registrations#destroy'

    # Passwords
    post 'settings/password',      to: 'devise/passwords#create', as: :user_password
    get  'settings/password/new',  to: 'devise/passwords#new',    as: :new_user_password
    get  'settings/password/edit', to: 'devise/passwords#edit',   as: :edit_user_password
    put  'settings/password',      to: 'devise/passwords#update'
  end

  get 'user/:username',           to: 'users#show',       as: :user
  get 'user/:username/comments',  to: 'users#comments',   as: :user_comments
  get 'user/:username/submitted', to: 'users#submitted',  as: :user_submitted
  get 'user/:username/starred',   to: 'users#starred',    as: :user_starred
  get 'user/:username/completed', to: 'users#completed',  as: :user_completed

  get 'challenges/easy',   to: 'challenges#easy'
  get 'challenges/medium', to: 'challenges#medium'
  get 'challenges/hard',   to: 'challenges#hard'

  resources :challenges do
    resources :comments
  end

  get 'tag/:name', to: 'tags#show', as: :tag
  resources :tags, only: :index
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:github]

  before_save :nilify_blanks

  has_many :challenges
  has_many :completed_challenges
  has_many :comments

  validates :username, presence: true
  validates :username, uniqueness: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.nickname
      user.image = auth.info.image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.github_data'] && session['devise.github_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end
end

private

def nilify_blanks
  attributes.each do |column, _value|
    self[column].present? || self[column] = nil
  end
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  provider               :string(255)
#  uid                    :string(255)
#  username               :string(255)
#  image                  :string(255)
#

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'GitHub') if is_navigational_format?
    else
      session['devise.github_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user

  def show
  end

  def comments
  end

  def submitted
  end

  def starred
  end

  def completed
  end

  private

  def find_user
    @user = User.find_by(username: params[:username])
  end
end

app/views/users/_tabs.html.erb
<nav class="profile-tabs">
  <ul>
    <li class="tab1 <%= add_active?(user_path(@user.username)) %>"><%= link_to 'profile', user_path(@user.username) %></li>
    <li class="tab2 <%= add_active?(user_comments_path(@user.username)) %>"><%= link_to 'comments', user_comments_path(@user.username) %></li>
    <li class="tab3 <%= add_active?(user_submitted_path(@user.username)) %>"><%= link_to 'submitted', user_submitted_path(@user.username) %></li>
    <li class="tab4 <%= add_active?(user_starred_path(@user.username)) %>"><%= link_to 'starred', user_starred_path(@user.username) %></li>
    <li class="tab5 <%= add_active?(user_completed_path(@user.username)) %>"><%= link_to 'completed', user_completed_path(@user.username) %></li>
  </ul>
</nav>

app/views/users/comments.html.erb
<%= render 'tabs' %>

<div class='user-comments'>
  <% @user.comments.each do |comment| %>
    <p class='comment__tagline'>
      <%= link_to comment.challenge.name, challenge_path(comment.challenge) %>
      <span class='post-owner'>by <%= link_to comment.challenge.user.username, user_path(comment.challenge.user.username) %></span>
    </p>

    <%= render partial: 'challenges/comment', locals: {comment: comment, challenge: comment.challenge} %>
  <% end %>
</div>

app/views/users/completed.html.erb
<%= render 'tabs' %>

app/views/users/show.html.erb
<%= render 'tabs' %>

<div class="user-info-box">
  <%= image_tag @user.image %>
  <h3><%= @user.username %></h3>
  <div><%= @user.challenges.count %> challenges</div>
  <div><%= @user.comments.count %> comments</div>
</div>

app/views/users/starred.html.erb
<%= render 'tabs' %>

app/views/users/submitted.html.erb
<%= render 'tabs' %>