config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:sessions, :registrations, :passwords],
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: 'registrations'
    }

  root 'challenges#index'

  # Default Devise routes
  #
  # Sessions
  # new_user_session     GET    /users/sign_in(.:format)  devise/sessions#new
  # user_session         POST   /users/sign_in(.:format)  devise/sessions#create
  # destroy_user_session DELETE /users/sign_out(.:format) devise/sessions#destroy
  #
  # Registrations
  # cancel_user_registration GET    /users/cancel(.:format)  registrations#cancel
  # user_registration        POST   /users(.:format)         registrations#create
  # new_user_registration    GET    /users/sign_up(.:format) registrations#new
  # edit_user_registration   GET    /users/edit(.:format)    registrations#edit
  #                          PATCH  /users(.:format)         registrations#update
  #                          PUT    /users(.:format)         registrations#update
  #                          DELETE /users(.:format)         registrations#destroy
  #
  # Passwords
  # user_password      POST  /users/password(.:format)      devise/passwords#create
  # new_user_password  GET   /users/password/new(.:format)  devise/passwords#new
  # edit_user_password GET   /users/password/edit(.:format) devise/passwords#edit
  #                    PATCH /users/password(.:format)      devise/passwords#update
  #                    PUT   /users/password(.:format)      devise/passwords#update

  devise_scope :user do
    # Sessions
    get    'login',  to: 'devise/sessions#new',     as: :new_user_session
    post   'login',  to: 'devise/sessions#create',  as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session

    # Registrations
    get    'signup',           to: 'registrations#new',    as: :new_user_registration
    post   'settings/account', to: 'registrations#create', as: :user_registration
    get    'settings/account', to: 'registrations#edit',   as: :edit_user_registration
    put    'settings/account', to: 'registrations#update'
    delete 'settings/account', to: 'registrations#destroy'

    # Passwords
    post 'settings/password',      to: 'devise/passwords#create', as: :user_password
    get  'settings/password/new',  to: 'devise/passwords#new',    as: :new_user_password
    get  'settings/password/edit', to: 'devise/passwords#edit',   as: :edit_user_password
    put  'settings/password',      to: 'devise/passwords#update'
  end

  get 'user/:username',           to: 'users#show',       as: :user
  get 'user/:username/comments',  to: 'users#comments',   as: :user_comments
  get 'user/:username/submitted', to: 'users#submitted',  as: :user_submitted
  get 'user/:username/starred',   to: 'users#starred',    as: :user_starred
  get 'user/:username/completed', to: 'users#completed',  as: :user_completed

  get 'challenges/easy',   to: 'challenges#easy'
  get 'challenges/medium', to: 'challenges#medium'
  get 'challenges/hard',   to: 'challenges#hard'

  resources :challenges do
    resources :comments
  end

  get 'tag/:name', to: 'tags#show', as: :tag
  resources :tags, only: :index
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  enum difficulty: [:easy, :medium, :hard]

  belongs_to :user
  has_many :user_completions, class_name: 'CompletedChallenge'

  has_many :challenge_tags, dependent: :destroy
  has_many :tags, through: :challenge_tags
  accepts_nested_attributes_for :challenge_tags, allow_destroy: true

  has_many :comments, dependent: :destroy

  validates :name, :short_description, :long_description, :user_id, :difficulty,
            :challenge_tags, presence: true
  validates :name, :short_description, :long_description, uniqueness: true
end

# == Schema Information
#
# Table name: challenges
#
#  id                :integer          not null, primary key
#  name              :string(255)
#  short_description :text(65535)
#  long_description  :text(65535)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  user_id           :integer
#  difficulty        :integer
#

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :authenticate_user!, except: [:easy, :medium, :hard, :index, :show]
  before_action :find_challenge, only: [:show, :edit, :update, :destroy]

  def easy
    @easy = Challenge.where(difficulty: 0)
  end

  def medium
    @medium = Challenge.where(difficulty: 1)
  end

  def hard
    @hard = Challenge.where(difficulty: 2)
  end

  def index
    @challenges = Challenge.all
  end

  def show
    @comment = Comment.new
    @comment.challenge_id = @challenge.id
  end

  def new
    @challenge = current_user.challenges.build
    @challenge_tags = @challenge.challenge_tags.build
  end

  def create
    @challenge = current_user.challenges.build(challenge_params)

    if @challenge.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    # Uncomment to add new tag select in edit view
    # @challenge_tags = @challenge.challenge_tags.build

    redirect_to root_path unless @challenge.user_id == current_user.id
  end

  def update
    if @challenge.update(challenge_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @challenge.destroy if @challenge.user_id == current_user.id
    redirect_to root_path
  end

  private

  def challenge_params
    params.require(:challenge).permit(
      :name, :short_description, :long_description, :user_id, :difficulty,
      challenge_tags_attributes: [:id, :tag_id]
    )
  end

  def find_challenge
    @challenge = Challenge.find(params[:id])
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_challenge.html.erb
<% challenges.each do |challenge| %>
  <section class='challenge'>
    <h3><%= link_to challenge.name, challenge_path(challenge) %></h3>

    <hr>

    <p><%= challenge.short_description %></p>

    <ul class='challenge__tags'>
      <% challenge.tags.each do |tag| %>
        <li><%= link_to tag.name, tag_path(tag.name) %></li>
      <% end %>

      <li><%= link_to challenge.difficulty, url_for([:challenges, challenge.difficulty]) %></li>
    </ul>
  </section>
<% end %>

app/views/challenges/_comment.html.erb
<div class='comment'>
  <p class='comment__tagline'>

  <%= link_to comment.user.username, user_path(comment.user.username), class: "username #{'challenge-owner' if challenge.user_id == comment.user.id}" %>

    <span class='timestamp'>
      <%= distance_of_time_in_words(Time.now, comment.created_at) %> ago
      <% if comment.created_at != comment.updated_at %>
      * (last edited <%= distance_of_time_in_words(Time.now, comment.updated_at) %> ago)
      <% end %>
    </span>

  </p>

  <p class='comment__body'><%= comment.body %></p>

    <% if user_signed_in? %>
      <ul class='actions'>
        <!-- TODO: add comment replying and context -->
        <li><a href='#'>reply</a></li>
        <!-- <li><a href='#'>context</a></li> -->

        <% if owns_content?(comment) %>
          <li><%= link_to 'edit', edit_challenge_comment_path(challenge, comment) %></li>
          <li><%= link_to 'delete', challenge_comment_path(challenge, comment), method: :delete, data: { confirm: 'Really delete the comment?' } %></li>
        <% end %>
      </ul>
    <% end %>
</div>

app/views/challenges/_form.html.erb
<%= form_for(@challenge) do |f| %>
  <%= f.text_field :name, autofocus: true, placeholder: 'challenge name' %>

  <%= f.text_field :short_description, placeholder: 'short description' %>

  <%= f.text_area :long_description, placeholder: 'long description' %>

  <%= f.select(:difficulty, Challenge.difficulties.keys.map {|difficulty| [difficulty]}, prompt: 'Select a difficulty') %>

  <%= f.fields_for :challenge_tags do |tag| %>
    <%= tag.collection_select(:tag_id, Tag.all, :id, :name, prompt: 'Select a tag') %>
  <% end %>

  <%= f.submit 'Submit' %>
<% end %>

app/views/challenges/easy.html.erb
<% if @easy.empty? %>
  <p>No easy challenges</p>
<% else %>
  <%= render partial: 'challenges/challenge', locals: { challenges: @easy } %>
<% end %>

app/views/challenges/edit.html.erb
<div class="form form--challenge">
  <h3>Edit Challenge</h3>
  <hr>

  <%= render 'form' %>
</div>

app/views/challenges/hard.html.erb
<% if @hard.empty? %>
  <p>No hard challenges</p>
<% else %>
  <%= render partial: 'challenges/challenge', locals: { challenges: @hard } %>
<% end %>

app/views/challenges/index.html.erb
<%= render partial: 'challenge', locals: { challenges: @challenges } %>

<% if user_signed_in? %>
  <%= link_to 'New Challenge', new_challenge_path, class: 'button' %>
<% end %>

app/views/challenges/medium.html.erb
<% if @medium.empty? %>
  <p>No medium challenges</p>
<% else %>
  <%= render partial: 'challenges/challenge', locals: { challenges: @medium } %>
<% end %>

app/views/challenges/new.html.erb
<div class="form form--challenge">
  <h3>Submit a Challenge</h3>
  <hr>

  <%= render 'form' %>
</div>

app/views/challenges/show.html.erb
<section class='challenge'>
  <h3><%= @challenge.name %></h3>

  <% if user_signed_in? && owns_content?(@challenge) %>
    <ul class='actions'>
      <li><%= link_to 'edit', edit_challenge_path(@challenge) %></li>
      <li><%= link_to 'delete', challenge_path(@challenge), method: :delete, data: { confirm: 'Really delete the challenge?' } %></li>
    </ul>
  <% end %>

  <hr>

  <p><%= @challenge.short_description %></p>
  <p><%= @challenge.long_description %></p>

  <ul class='challenge__tags'>
    <% @challenge.tags.each do |tag| %>
      <li><%= link_to tag.name, tag_path(tag.name) %></li>
    <% end %>
    <li><%= link_to @challenge.difficulty, url_for([:challenges, @challenge.difficulty]) %></li>
  </ul>
</section>

<section class='comments'>
  <h3>Comments</h3>
  <hr>

  <% if @challenge.comments.empty? %>
    <p>No Comments</p>
  <% else %>
    <%= render partial: 'comment', locals: {challenge: @challenge}, collection: @challenge.comments %>
  <% end %>
</section>

<% if user_signed_in? %>
  <section class='form'>
    <h3>Post a Comment</h3>
    <hr>
    <%= render partial: 'comments/form' %>
  </section>
<% end %>